FROM oven/bun:1.3.0
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package.json bun.lock turbo.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/auth/package.json packages/auth/package.json
COPY packages/config-eslint/package.json packages/config-eslint/package.json
COPY packages/config-tailwind/package.json packages/config-tailwind/package.json
COPY packages/config-typescript/package.json packages/config-typescript/package.json
COPY packages/database/package.json packages/database/package.json
COPY packages/shared/package.json packages/shared/package.json
COPY packages/ui/package.json packages/ui/package.json

RUN bun install --frozen-lockfile

CMD ["bun", "run", "--filter", "@repo/api", "dev"]
